os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="libcurl/7.50.3"
    - CONAN_USERNAME="lasote"
    - CONAN_CHANNEL="testing"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1
    - CONAN_STABLE_BRANCH_PATTERN="release/*"

  matrix:
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_USE_DOCKER=1

matrix:
   include:
       - os: osx 
         osx_image: xcode8.2 # apple-clang 8.2
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx
         osx_image: xcode8.2 # apple-clang 8.2
         language: generic
         env: CONAN_CURRENT_PAGE=2

       - os: osx 
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env: CONAN_CURRENT_PAGE=2

       - os: osx
         osx_image: xcode6.4 # apple-clang 6.1
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx
         osx_image: xcode6.4 # apple-clang 6.1
         language: generic
         env: CONAN_CURRENT_PAGE=2

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
